[package]
name = "nx-driver"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "nx"
path = "src/main.rs"

[dependencies]
nx-lexer = { path = "../nx-lexer" }
nx-ast = { path = "../nx-ast" }
nx-parser = { path = "../nx-parser" }
nx-types = { path = "../nx-types" }
nx-codegen = { path = "../nx-codegen" }
nx-interp = { path = "../nx-interp" }
