[package]
name = "nx-interp"
version = "0.4.0"
edition = "2021"
license = "MIT"

[lib]
name = "nx_interp"
path = "src/lib.rs"

[dependencies]
nx-ast = { path = "../nx-ast" }
nx-lexer = { path = "../nx-lexer" }
nx-parser = { path = "../nx-parser" }
nx-ir = { path = "../nx-ir" }
nx-types = { path = "../nx-types" }
