[package]
name = "nx-e2e"
version = "0.4.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "nx_e2e"
path = "src/lib.rs"

[dependencies]
nx-lexer = { path = "../nx-lexer" }
nx-ast = { path = "../nx-ast" }
nx-parser = { path = "../nx-parser" }
nx-types = { path = "../nx-types" }
nx-codegen = { path = "../nx-codegen" }